{% set name = "exceptiongroup" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exceptiongroup-{{ version }}.tar.gz
  sha256: 91f5c769735f051a4290d52edd0858999b57e5876e9f85937691bd4c9fa3ed68

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - flit-scm
    - wheel
  run:
    - python

test:
  imports:
    - exceptiongroup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/exceptiongroup/
  summary: Backport of PEP 654 (exception groups)
  description: |
    "This is a backport of the BaseExceptionGroup and ExceptionGroup classes from Python 3.11.
    It contains the following:
      * The exceptiongroup.BaseExceptionGroup and exceptiongroup.ExceptionGroup classes
      * A utility function (exceptiongroup.catch()) for catching exceptions possibly nested in an exception group
      * Patches to the TracebackException class that properly formats exception groups (installed on import)
      * An exception hook that handles formatting of exception groups through TracebackException (installed on import)
      * Special versions of some of the functions from the traceback module"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/agronholm/exceptiongroup
  doc_url: https://docs.python.org/3/library/exceptions.html

extra:
  recipe-maintainers:
    - xylar
